// Shared with the homepage "פרויקטים נבחרים" teaser and the full /projects page.
export const projects = [
    {
        id: 'culinary-north',
        title: 'קולינריה צפון',
        subtitle: 'פלטפורמה לעולם הקולינריה בצפון',
        typeLabel: 'פרויקט חי',
        image: '/images/culinary-north/logo.webp',
        accent: '#d4b483',
        desc: 'יש משהו מעניין כשמפתח בונה מוצר לעולם שהוא מכיר מהצד השני. מקצב המטבח — לפלטפורמה חיה של משרות, קהילה ואנשי מקצוע.',
        link: 'https://culinary-north.co.il',
        ctaText: 'צפו באתר',
        story: '/culinary-north',
        storyCta: 'הסיפור',
    },
    {
        id: 'le-france',
        title: 'הצרפתייה הקטנה',
        subtitle: 'המטבח · אתר הזמנות חי',
        typeLabel: 'פרויקט חי',
        image: '/images/le-france/logo-wordmark.png',
        imageWide: true,
        accent: '#d4c7a8',
        desc: 'אתר לצרפתייה הקטנה – המטבח, עם מסלולי הזמנה נפרדים. מאחורי הקלעים ההזמנות ממשיכות דרך TakeEat.',
        link: 'https://hamitbah.hazarfatia.co.il',
        ctaText: 'צפו באתר',
        story: '/le-france',
        storyCta: 'הסיפור',
    },
    {
        id: 'bina',
        title: 'בינה לבנייה',
        subtitle: 'אתר עסקי שנבנה מאפס',
        typeLabel: 'פרויקט אתר',
        image: '/images/fulllogo_nobuffer.jpeg',
        accent: '#35d0ff',
        desc: 'עסק בנייה בלי נוכחות דיגיטלית מקצועית. בניתי אתר תדמית מותאם מותג, עם SEO ויצירת קשר מהירה — נוכחות מקצועית ברשת ויותר פניות מגוגל.',
        link: 'https://www.binalb.com/',
        ctaText: 'צפו באתר',
    },
    {
        id: 'bar',
        title: 'בר בן אבו',
        subtitle: 'פרויקט עבר · אתר תדמית לאדריכל',
        typeLabel: 'פרויקט עבר',
        image: '/images/barLogo.png',
        accent: '#7c5cff',
        desc: 'אתר מינימליסטי ברמת סטודיו להצגת פרויקטי אדריכלות — גלריה, UX נקי ומיתוג דיגיטלי ברמה גבוהה. אינו לקוח פעיל כיום.',
        link: 'https://bar-app-self.vercel.app/',
        ctaText: 'צפו באתר',
    },
    {
        id: 'appointed',
        title: 'Appointed',
        subtitle: 'מוצר · ניהול תורים לעסקים',
        typeLabel: 'פרויקט נוסף',
        image: '/images/appointedCloud.png',
        accent: '#a78bfa',
        desc: 'מערכת תורים אונליין, יומן, תזכורות וניהול לקוחות מהטלפון. פחות מייצג את המיקוד שלי כיום — נשמר כאן כפרויקט נוסף.',
        link: 'https://appointed.cloud',
        ctaText: 'צפו במערכת',
    },
]
