// Shared with the homepage "פרויקטים נבחרים" teaser and the full /projects page.
export const projects = [
    {
        id: 'le-france',
        title: 'הצרפתייה הקטנה',
        subtitle: 'Case Study · אתר חי + TakeEat',
        typeLabel: 'Case Study',
        image: '/images/le-france/logo-green.png',
        accent: '#34d399',
        desc: 'מסעדה צרפתית־ישראלית בכשרות מהודרת — אתר דיגיטלי חי ומערכת הזמנות מבוססת TakeEat, רשומה גם כמסעדה במערכת ChefSync.',
        link: 'https://la-france-omega.vercel.app/',
        ctaText: 'לצפייה באתר החי',
    },
    {
        id: 'bina',
        title: 'בינה לבנייה',
        subtitle: 'אתר עסקי שנבנה מאפס',
        typeLabel: 'פרויקט אתר',
        image: '/images/fulllogo_nobuffer.jpeg',
        accent: '#35d0ff',
        desc: 'עסק בנייה בלי נוכחות דיגיטלית מקצועית. בניתי אתר תדמית מותאם מותג, עם SEO ויצירת קשר מהירה — נוכחות מקצועית ברשת ויותר פניות מגוגל.',
        link: 'https://www.binalb.com/',
        ctaText: 'צפו באתר',
    },
    {
        id: 'bar',
        title: 'בר בן אבו',
        subtitle: 'פרויקט עבר · אתר תדמית לאדריכל',
        typeLabel: 'פרויקט עבר',
        image: '/images/barLogo.png',
        accent: '#7c5cff',
        desc: 'אתר מינימליסטי ברמת סטודיו להצגת פרויקטי אדריכלות — גלריה, UX נקי ומיתוג דיגיטלי ברמה גבוהה. אינו לקוח פעיל כיום.',
        link: 'https://bar-app-self.vercel.app/',
        ctaText: 'צפו באתר',
    },
    {
        id: 'appointed',
        title: 'Appointed',
        subtitle: 'מוצר · ניהול תורים לעסקים',
        typeLabel: 'פרויקט נוסף',
        image: '/images/appointedCloud.png',
        accent: '#a78bfa',
        desc: 'מערכת תורים אונליין, יומן, תזכורות וניהול לקוחות מהטלפון. פחות מייצג את המיקוד שלי כיום — נשמר כאן כפרויקט נוסף.',
        link: 'https://appointed.cloud',
        ctaText: 'צפו במערכת',
    },
]
